# Generated by Django 4.0.4 on 2022-06-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_finalorder_price_alter_finalorder_shipping_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalOrder',
        ),
    ]
